### ISSUE TITLE
Plugin not showing up in Shaarli Plugin admin due to _ in filename

### ISSUE THREAD

**Issue by 14ngr15t** [ArthurHoaro/code-coloration#1]
I installed this to my Shaarli /plugins folder via git, but it didn't show up in the plugins list.  I had this issue with some other plugins - it seems anything with a "-" or "_" in the .php filename does not work.  I renamed both "code_coloration.php" and "code_coloration.meta"  without the _ and the plugin showed up for activation.

However, this probably has broken something when actually using the plugin.  I haven't tested thoroughly yet to find out.  Just wanted you to know about this issue in the latest release of Shaarli .7.0

**Comment by ArthurHoaro** [comment]
The folder and the files must have the same name. Files use a `_`, and the directory (Github project name) uses a `-`. That's why I wasn't showing up. I'll fix this by adding a subdirectory.

Rename the files to their initial names, and rename the plugin folder to `code_coloration`. You should be fine with this.

**Comment by 14ngr15t** [comment]
Thanks!  That worked!

**Comment by ArthurHoaro** [comment]
Fixed.
